version: "3.3"

services:

  api-user:
    build:
      context: ./api-user
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"

  api-contact:
    build:
      context: ./api-contact
      dockerfile: Dockerfile.dev
    ports:
      - "8082:8082"
    depends_on:
      - "api-user"

  api-group:
    build:
      context: ./api-group
      dockerfile: Dockerfile.dev
    ports:
      - "8083:8083"
    depends_on:
      - "api-user"
  
  api-message:
    build:
      context: ./api-message
      dockerfile: Dockerfile.dev
    ports:
      - "8084:8084"
    depends_on:
      - "api-user"
  
  api-smtp-config:
    build:
      context: ./api-smtp-config
      dockerfile: Dockerfile.dev
    ports:
      - "8085:8085"
    depends_on:
      - "api-user"